// <auto-generated />
namespace MvcApplication4.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class MLA2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MLA2));
        
        string IMigrationMetadata.Id
        {
            get { return "201412262312027_MLA2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
