// <auto-generated />
namespace MvcApplication4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class MLA59 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MLA59));
        
        string IMigrationMetadata.Id
        {
            get { return "201512112356149_MLA59"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
