// <auto-generated />
namespace MvcApplication4.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class MLA3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MLA3));
        
        string IMigrationMetadata.Id
        {
            get { return "201501021319154_MLA3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
