// <auto-generated />
namespace MvcApplication4.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class MLA4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MLA4));
        
        string IMigrationMetadata.Id
        {
            get { return "201501031722094_MLA4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
